### ISSUE TITLE
Simple component test for Button component

### ISSUE THREAD

**Issue by fauzzi** [agilworld/eAwesome#4]
Please refer to link below for component test.

https://reactnativetesting.io/component/intro.html

It is possible will have a simple component test for Button component? If yes, please go ahead and let me know on this able to implement.

The folder stack later like bellow
```js
- components
   - __tests__
        Button.spec.js
```

To run the test from terminal
$ npm run test

To create the coverage from terminal
$ npm run test -- --coverage

To update snapshot from terminal
$ npm run test -- --u

Thank you in advance.

@agilworld

**Comment by agilworld** [comment]
Done! implemented

**Comment by fauzzi** [comment]
Following the test case below:
Good Case - Pass some props
  - Should render correctly
  - Clicking button

Bad Case - Not pass any prop
   - Should render correctly

To create the coverage from terminal
$ npm run test -- --coverage

When have an update the snapshot, if need to update can use the below command
$ npm run test -- --u

Can refer to this attach to create snapshot.
<img width="570" alt="Screenshot 2020-10-14 at 9 07 01 PM" src="https://user-images.githubusercontent.com/20034987/96000605-452b1500-0e61-11eb-8179-77ae1c1ed782.png">

@agilworld
